name: SonarQube Code Analysis

on:
  push:
    branches:
      - '**'  # Triggers for all branches
  pull_request:
    branches:
      - '**'  # Triggers for all pull requests

jobs:
  sonarcloud:
    name: SonarQube Analysis
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the Git Repository
        uses: actions/checkout@v4

      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Add gradlew permission
        run: chmod +x gradlew

      - name: Run unit test
        run: ./gradlew test

      - name: Cache SonarCloud dependencies
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonarcloud-${{ hashFiles('**/sonar-project.properties') }}
          restore-keys: |
            ${{ runner.os }}-sonarcloud-

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # SonarCloud Token from GitHub Secrets
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=<soydoradesu_adpro-module> \
            -Dsonar.organization=<soydoradesu> \
            -Dsonar.host.url=https://sonarcloud.io
